### PR TITLE
Added configuration for Paper

### PR DESCRIPTION
**Pull request by n0toose**
https://papermc.io

### CODE REVIEW

**Comment by agowa** [comment]
Thanks for using this and for your contribution, but I don't want to add every single server out there, I just added the two most common ones Forge and Vanialla. If Paper becomes the new *it*, I may consider adding it. That's why I also did not add Spigot or Sponge.

**Comment by n0toose** [comment]
> Thanks for using this and for your contribution, but I don't want to add every single server out there, I just added the two most common ones Forge and Vanialla. If Paper becomes the new _it_, I may consider adding it. That's why I also did not add Spigot or Sponge.

Understood.

**Comment by n0toose** [comment]
Hi @agowa338, mind if I ask why this pull request was reopened?

**Comment by n0toose** [comment]
Oh, I guess that's nice!

**Comment by agowa** [comment]
Someone wrote me if I would mind accepting these kind of pr, as that would allow them to easily deploy servers using docker. They can include this repository into there docker one as a git submodule/subtree and as others (in this case you) provided the necessary regex pattern, there is a bigger win in merging it than in denying. (Also I got a notification as someone created another pr for adding some servers that reminded me about that).
Therefore thanks for your contribution ;-)

**Comment by n0toose** [comment]
> Someone wrote me if I would mind accepting these kind of pr, as that would allow them to easily deploy servers using docker. They can include this repository into there docker one as a git submodule/subtree and as others (in this case you) provided the necessary regex pattern, there is a bigger win in merging it than in denying.
> Therefore thanks for your contribution ;-)

Oh, no worries! Perhaps splitting the lines per .jar file could make the script look much cleaner, though. If you could also e-mail me that project, that'd be appreciated, because I'd be able to use it for my own machines more easily.

**Comment by agowa** [comment]
I don't have the link to that project, I even don't know if it was already started.
But you're right it's about time for a rebase...

**Pull request merged**
