### PR TITLE
Add easier way to configure RAM assignment

### PR DESCRIPTION
**Pull request by mivalsten**
Based on answers from issue #10 

Also removed HTML tags from README.md to be clean markdown.

### CODE REVIEW

**Comment by TheSageMarmot** [comment]
I am still quite new to systemd. Am I correctly understanding that each instance will now be required to have the config file? Where are the default values now defined? I like that the values can be defined per MC instance.

```
/usr/bin/java -server -Xms${MCMINMEM} -Xmx${MCMAXMEM}
```

**Comment by mivalsten** [comment]
@TheSageMarmot 
So, long story short, I suck at using git and due to that I pushed incomplete file. :D
Defaults are in line 33, and line 35 defines path to per-instance configuration.

Thanks for pointing this out.

**Comment by agowa** [comment]
Thanks for the pr and did I really do that to the markdown file? It is horrible to look at what you did when you were junger...

**Comment by mivalsten** [comment]
Happy to help. :)

**Pull request merged**
